// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CartBox: typeof import('./components/organisms/CartBox.vue')['default']
    CartButton: typeof import('./components/atoms/CartButton.vue')['default']
    Header: typeof import('./components/organisms/Header.vue')['default']
    LeftNav: typeof import('./components/organisms/LeftNav.vue')['default']
  }
}

export { }
